export const FETCH_CARS = 'FETCH_CARS';
export const SEARCH_CARS_BY_BRAND = 'SEARCH_CARS_BY_BRAND';
export const SEARCH_CARS_BY_COLOR = 'SEARCH_CARS_BY_COLOR';
export const SEARCH_CARS_BY_ENGINE = 'SEARCH_CARS_BY_ENGINE';
export const SEARCH_CARS_BY_DRIVE = 'SEARCH_CARS_BY_DRIVE';